name: bloc_form_web_plus
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 0.1.3
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc_form_plus: ^0.1.3
  animations: ^2.0.11
  flutter_syntax_view: ^4.1.7
  flash: ^3.1.1
  url_launcher: ^6.3.2
  flutter_markdown: ^0.7.7+1
  auto_size_text: ^3.0.0
  liquid_progress_indicator_v2: ^0.5.0
  rxdart: ^0.28.0
  google_fonts: ^6.3.0

#  flutter_keyboard_visibility_temp_fork: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
dependency_overrides:
  flutter_keyboard_visibility_web: 0.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
  assets:
    - lib/examples/
