name: bloc_form_plus

on:
  push:
    paths:
      - "packages/bloc_form_plus/**"
      - ".github/workflows/bloc_form_plus.yaml"

  pull_request:
    paths:
      - "packages/bloc_form_plus/**"
      - ".github/workflows/bloc_form_plus.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/bloc_form_plus

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: flutter test
