name: Bloc Form Plus Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      contents: write # Grants write permission for the repository contents
      pages: write    # Grants write permission to update GitHub Pages
      id-token: write # Required for some newer deployment actions
    runs-on: ubuntu-latest
    env:
      working-directory: ./bloc_form_web_plus
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # important for pushing

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: stable
          cache: true

      - name: Enable Flutter web
        run: flutter config --enable-web
        working-directory: ${{ env.working-directory }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ env.working-directory }}

      - name: Build Flutter web
        run: flutter build web --release
        working-directory: ${{ env.working-directory }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.working-directory }}/build/web
          keep_files: true
          user_name: github-actions
          user_email: github-actions@github.com
